version: '3.3'
services:
  dev:
    container_name: react-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/my-app'
      - '/my-app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development